printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
proseWrap: preserve
endOfLine: lf

overrides:
  - files: "*.md"
    options:
      proseWrap: preserve
      printWidth: 100
  - files: ["*.yml", "*.yaml"]
    options:
      tabWidth: 2
      useTabs: false